spring.application.name=kassensystem
spring.profiles.active=dev
server.port=0

# --- App ---
spring.kassensystem.cashier.password=1234
spring.filialsystem.url=http://localhost:8080

# --- JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# --- RabbitMQ ---
spring.rabbitmq.exchange=${spring.application.name}.${spring.profiles.active}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.host=cow.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=tgamtfjc
spring.rabbitmq.password=LGl-i3KF-JuaNxoPrUGCNsffR9AYfo-i
spring.rabbitmq.virtual-host=tgamtfjc

# --- Actuator ---
management.endpoints.web.exposure.include=health, info