services:
  postgres:
    image: postgres:18.3
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vendix
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/vendix
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: pass

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8090

    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - app

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  app:
    driver: bridge