services:
  postgres:
    image: postgres:18.3
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vendix
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app

  redis:
    image: redis:8.6
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/data
    networks:
      - app

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  app:
    driver: bridge