# Server
server.port=0

# Application
spring.application.name=pos
spring.profiles.default=local
spring.profiles.active=local

# Oauth2
spring.security.oauth2.client.registration.keycloak.client-id=pos-app
spring.security.oauth2.client.registration.keycloak.client-secret=SKH8abWVDZZplBSn29QFQJlK7FBN1LFs