# Import shared properties
spring.config.import=classpath:shared.properties

# Server
server.port=0
server.reactive.session.cookie.name=REACTIVE_${spring.application.name}
server.servlet.session.cookie.name=SERVLET_${spring.application.name}

# Application
spring.application.name=pos
spring.profiles.default=local
spring.profiles.active=local

# Vendix
vendix.security.jwt.private-key=JSGJEkw471n4i0H4aX5sQamrTnXL/iKwTfTq3YLAWYA=

# Monitoring
management.endpoints.web.exposure.include=health, info, prometheus
management.endpoint.prometheus.access=read_only