# Server
server.port=0

# Application
spring.application.name=pos
spring.profiles.default=local
spring.profiles.active=local

# Oauth2
## Register Web
spring.security.oauth2.client.registration.keycloak.client-id=register-web
spring.security.oauth2.client.registration.keycloak.client-secret=${REGISTER_WEB_SECRET}
## Register App
spring.security.oauth2.client.registration.register-app.provider=keycloak
spring.security.oauth2.client.registration.register-app.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.register-app.client-id=register-app
spring.security.oauth2.client.registration.register-app.client-secret=${REGISTER_APP_SECRET}