# Request Header-Info
server.forward-headers-strategy=native

# Keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8090/realms/vendix
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/vendix