# Request Header-Info
server.forward-headers-strategy=native

# Vendix
vendix.security.rate-limit.is-enabled=false

# Keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8090/realms/vendix
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/vendix