<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.fhdw.vendix</groupId>
        <artifactId>pos-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>pos-app</artifactId>
    <packaging>jar</packaging>

    <name>pos-app</name>
    <description>pos-app</description>

    <dependencies>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>pos-api</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>pos-core</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>pos-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>pos-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-dev</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-spring-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>