<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.0</version>
        <relativePath/>
    </parent>

    <groupId>de.fhdw.vendix</groupId>
    <artifactId>vendix-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>vendix</name>
    <description>vendix</description>

    <modules>
        <module>pos</module>
        <module>store</module>
        <module>commons</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <vaadin.version>25.0.5</vaadin.version>
        <jwt.version>0.13.0</jwt.version>
        <jackson.version>3.0.4</jackson.version>
        <springdoc.version>3.0.1</springdoc.version>
        <pdfbox.version>3.0.6</pdfbox.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Source: https://mvnrepository.com/artifact/com.vaadin/vaadin-bom -->
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Source: https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-bom -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-bom</artifactId>
                <version>${jwt.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Source: https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-bom -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-bom</artifactId>
                <version>${springdoc.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>