# Server
server.port=0

# Application
spring.application.name=store
spring.profiles.default=local
spring.profiles.active=local

# Oauth2
vendix.keycloak.client.app-name=store-app
vendix.keycloak.client.web-name=store-web
## Store Web
spring.security.oauth2.client.registration.store-web.client-id=store-web
spring.security.oauth2.client.registration.store-web.client-secret=m3N8CZc6T2DFKn6Od6DcBFSRYP2aZyRR
spring.security.oauth2.client.registration.store-web.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.store-web.scope=openid,profile,email
spring.security.oauth2.client.registration.store-web.provider=keycloak
## Store App
spring.security.oauth2.client.registration.store-app.client-id=store-app
spring.security.oauth2.client.registration.store-app.client-secret=SRsh82xbFdEeMJYSUEyfSjJXVBM9htht
spring.security.oauth2.client.registration.store-app.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.store-app.scope=openid,profile,email
spring.security.oauth2.client.registration.store-app.provider=keycloak