# Server
server.port=0

# Application
spring.application.name=store
spring.profiles.default=local
spring.profiles.active=local

# Oauth2
## Store Web
spring.security.oauth2.client.registration.keycloak.client-id=store-web
spring.security.oauth2.client.registration.keycloak.client-secret=${STORE_WEB_SECRET}
## Store App
spring.security.oauth2.client.registration.store-app.provider=keycloak
spring.security.oauth2.client.registration.store-app.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.store-app.client-id=store-app
spring.security.oauth2.client.registration.store-app.client-secret=${STORE_APP_SECRET}