<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.fhdw.vendix</groupId>
    <artifactId>commons-bom</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>commons-bom</name>
    <description>commons-bom</description>

    <properties>
        <commons.version>${project.version}</commons.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- commons-api -->
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-api</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <!-- commons-core -->
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-core</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <!-- commons-spring -->
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-spring-data-caching</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-spring-data-persistance</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-spring-security</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-spring-web</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-spring-vaadin</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-spring-app</artifactId>
                <version>${commons.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-spring-starter</artifactId>
                <version>${commons.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
