global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: /actuator/prometheus

    http_sd_configs:
      - url: http://host:8080/prometheus/targets
        refresh_interval: 5s