scrape_configs:
  - job_name: 'store-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['store-app:8080']

  - job_name: 'pos-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pos-app:8080']