spring.application.name=filialensystem
spring.profiles.active=dev

# --- App ---
spring.security.enabled=false

# --- JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Datasource ---
spring.datasource.driver-class-name=org.postgresql.Driver

# --- RabbitMQ ---
spring.rabbitmq.exchange=${spring.application.name}.${spring.profiles.active}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.host=cow.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=tgamtfjc
spring.rabbitmq.password=LGl-i3KF-JuaNxoPrUGCNsffR9AYfo-i
spring.rabbitmq.virtual-host=tgamtfjc

# --- Actuator ---
management.endpoints.web.exposure.include=health, info