spring.application.name=logistik
server.port=${PORT:8081}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false
vaadin.launch-browser=true

# ===Eigene Tabellen===
#spring.datasource.url=jdbc:postgresql://ep-bold-darkness-agi75a1e-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_nb2oUpM1CmPX


#spring.jpa.hibernate.ddl-auto=update
#vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,com.example.application
#spring.jpa.defer-datasource-initialization = true
#spring.sql.init.mode = never


# ---- Datasource -----
spring.datasource.url=jdbc:postgresql://ep-still-sky-agzvzwl9-pooler.c-2.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nb2oUpM1CmPX&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nb2oUpM1CmPX
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- Spring Jpa ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- RabbitMQ ----
spring.rabbitmq.exchange=${spring.application.name}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.host=cow.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=tgamtfjc
spring.rabbitmq.password=LGl-i3KF-JuaNxoPrUGCNsffR9AYfo-i
spring.rabbitmq.virtual-host=tgamtfjc