spring.application.name=kassensystem
spring.profiles.active=dev

# --- App ---
spring.kassensystem.cashier.password=1234

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Datasource ---
spring.datasource.driver-class-name=org.postgresql.Driver
