<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.fhdw.vendix</groupId>
    <artifactId>store-bom</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>store-bom</name>
    <description>store-bom</description>

    <properties>
        <store.version>${project.version}</store.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>store-api</artifactId>
                <version>${store.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>store-core</artifactId>
                <version>${store.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>store-web</artifactId>
                <version>${store.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>store-ui</artifactId>
                <version>${store.version}</version>
            </dependency>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>store-app</artifactId>
                <version>${store.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>