# Neon PostgreSQL Konfiguration
spring.datasource.url=jdbc:postgresql://ep-still-sky-agzvzwl9-pooler.c-2.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nb2oUpM1CmPX&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nb2oUpM1CmPX
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Logging
logging.level.fhdw.de.einkauf_service.amqp=INFO

# AMQP/RabbitMQ Konfiguration
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.host=cow.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=tgamtfjc
spring.rabbitmq.password=LGl-i3KF-JuaNxoPrUGCNsffR9AYfo-i
spring.rabbitmq.virtual-host=tgamtfjc
amqp.central-exchange=central
amqp.central-application=purchase-service
