# lokale DB PostgreSQL Konfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=geheim123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=30
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=2000
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20

# JPA/Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Logging
logging.level.fhdw.de.einkauf_service.amqp=INFO

# Management Endpoints - Actuator und Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# AMQP/RabbitMQ Konfiguration
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.host=cow.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=tgamtfjc
spring.rabbitmq.password=LGl-i3KF-JuaNxoPrUGCNsffR9AYfo-i
spring.rabbitmq.virtual-host=tgamtfjc
amqp.central-exchange=central
amqp.central-application=purchase-service
