openapi: 3.0.0

info:
  title: Store API
  description: This API provides operations for managing articles and receipts within a store.
  version: 1.1.0

tags:
  - name: Article
    description: Operations related to articles.
  - name: Receipt
    description: Operations related to receipts.
  - name: Checkout
    description: Operations related to checkout, print and cancel of receipts.
  - name: Voucher
    description: Operations related to vouchers.

servers:
  - url: http://localhost:808/store
    description: Local development server. Port is set dynamically.

paths:
  /api/article/id/{id}:
    $ref: './paths/article_id.yaml'
  /api/article/gtin/{gtin}:
    $ref: './paths/article_gtin.yaml'
  /api/receipt/:
    $ref: './paths/receipt.yaml'
  /api/receipt/checkout:
    $ref: './paths/receipt_checkout.yaml'
  /api/receipt/{id}/print:
    $ref: './paths/receipt_id_print.yaml'
  /api/receipt/{id}/cancel:
    $ref: './paths/receipt_id_cancel.yaml'
  /api/voucher/{code}:
    $ref: './paths/voucher_code.yaml'
  /api/voucher/{code}/redeem:
    $ref: './paths/voucher_code_redeem.yaml'

components:
  schemas:
    PaymentMethod:
      $ref: './components/schemas/PaymentMethod.yaml'
    ReceiptStatus:
      $ref: './components/schemas/ReceiptStatus.yaml'
    ArticleDTO:
      $ref: './components/schemas/ArticleDTO.yaml'
    ReceiptDTO:
      $ref: './components/schemas/ReceiptDTO.yaml'
    CheckoutLineDTO:
      $ref: './components/schemas/CheckoutLineDTO.yaml'
    CheckoutRequestDTO:
      $ref: './components/schemas/CheckoutRequestDTO.yaml'
    CheckoutResponseDTO:
      $ref: './components/schemas/CheckoutResponseDTO.yaml'
    VoucherDTO:
      $ref: './components/schemas/VoucherDTO.yaml'