global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  # Vendix Store Spring Boot Actuator (Port 8080)
  - job_name: 'vendix-store'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 5s