<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.fhdw.vendix</groupId>
        <artifactId>vendix-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>commons-parent</artifactId>
    <packaging>pom</packaging>

    <name>commons</name>
    <description>commons</description>

    <modules>
        <module>bom</module>
        <module>api</module>
        <module>core</module>
        <module>spring</module>
        <module>ui</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>de.fhdw.vendix</groupId>
                <artifactId>commons-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>