apiVersion: 1

datasources:
  - name: Prometheus
    uid: vendix-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: "5s"

  - name: Loki
    uid: vendix-loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true