openapi: 3.0.0

info:
  title: Orchestrator
  description: d
  version: 1.0.0

tags:
  - name: Connection
    description: Operations related to Connections
  - name: Lock
    description: Operations related to Locks
  - name: Account
    description: Operations related to Accounts
  - name: Store
    description: Operations related to Stores

servers:
  - url: http://localhost:8080
    description: Local development server

security:
  - bearerAuth: [ ]

paths:
  /api/connection:
    get:
      operationId: getConnections
      description: d
      tags:
        - Connection
      parameters:
        - in: query
          name: targetId
          required: false
          description: d
          schema:
            type: integer
            format: int64
        - in: query
          name: targetType
          required: false
          description: d
          schema:
            $ref: "#/components/schemas/TargetType"
        - in: query
          name: instanceUUID
          required: false
          description: d
          schema:
            type: string
            format: uuid
        - in: query
          name: instanceHost
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: instanceServer
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: instancePort
          required: false
          description: d
          schema:
            type: integer
            minimum: 0
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/ConnectionDTO"
    post:
      operationId: postConnection
      description: d
      tags:
        - Connection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectionDTO"
      responses:
        201:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionDTO"
        409:
          description: d

  /api/connection/target/{target}/id/{id}:
    get:
      operationId: getConnectionByTarget
      description: d
      tags:
        - Connection
      parameters:
        - in: path
          name: target
          description: d
          required: true
          schema:
            $ref: "#/components/schemas/TargetType"
        - in: path
          name: id
          description: d
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionDTO"
        404:
          description: d
    delete:
      operationId: deleteConnectionByTarget
      description: d
      tags:
        - Connection
      parameters:
        - in: path
          name: target
          description: d
          required: true
          schema:
            $ref: "#/components/schemas/TargetType"
        - in: path
          name: id
          description: d
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: d

  /api/connection/uuid/{uuid}:
    get:
      operationId: getConnectionByInstanceUUID
      description: d
      tags:
        - Connection
      parameters:
        - in: path
          name: uuid
          description: d
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionDTO"
        404:
          description: d
    delete:
      operationId: deleteConnectionByInstanceUUID
      description: d
      tags:
        - Connection
      parameters:
        - in: path
          name: uuid
          description: d
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: d

  /api/lock:
    get:
      operationId: getLocks
      description: d
      tags:
        - Lock
      parameters:
        - in: query
          name: targetId
          required: false
          description: d
          schema:
            type: integer
            format: int64
        - in: query
          name: targetType
          required: false
          description: d
          schema:
            $ref: "#/components/schemas/TargetType"
        - in: query
          name: instanceUUID
          required: false
          description: d
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/LockDTO"
    post:
      operationId: postLock
      description: d
      tags:
        - Lock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LockDTO"
      responses:
        201:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LockDTO"
        409:
          description: d

  /api/lock/target/{target}/id/{id}:
    get:
      operationId: getLockByTarget
      description: d
      tags:
        - Lock
      parameters:
        - in: path
          name: target
          description: d
          required: true
          schema:
            $ref: "#/components/schemas/TargetType"
        - in: path
          name: id
          description: d
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LockDTO"
        404:
          description: d
    delete:
      operationId: deleteLockByTarget
      description: d
      tags:
        - Lock
      parameters:
        - in: path
          name: target
          description: d
          required: true
          schema:
            $ref: "#/components/schemas/TargetType"
        - in: path
          name: id
          description: d
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: d

  /api/lock/uuid/{uuid}:
    get:
      operationId: getAllLocksByInstanceUUID
      description: d
      tags:
        - Lock
      parameters:
        - in: path
          name: uuid
          description: d
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/LockDTO"
    delete:
      operationId: deleteAllLocksByInstanceUUID
      description: d
      tags:
        - Lock
      parameters:
        - in: path
          name: uuid
          description: d
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: d

  /api/account:
    get:
      operationId: getAccounts
      description: getAccounts
      tags:
        - Account
      parameters:
        - in: query
          name: id
          required: false
          description: d
          schema:
            type: integer
            format: int64
        - in: query
          name: uuid
          required: false
          description: d
          schema:
            type: string
            format: uuid
        - in: query
          name: username
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: password
          required: false
          description: d
          schema:
            type: string
            format: password
        - in: query
          name: firstName
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: middleName
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: lastName
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: phone
          required: false
          description: d
          schema:
            type: string
            format: phone
        - in: query
          name: email
          required: false
          description: d
          schema:
            type: string
            format: email
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/AccountDTO"

  /api/account/username/{username}:
    get:
      operationId: getAccountByUsername
      description: d
      tags:
        - Account
      parameters:
        - in: path
          name: username
          required: true
          description: d
          schema:
            type: string
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDTO"
        404:
          description: d

  /api/account/uuid/{uuid}:
    get:
      operationId: getAccountByUUID
      description: d
      tags:
        - Account
      parameters:
        - in: path
          name: uuid
          required: true
          description: d
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDTO"
        404:
          description: d

  /api/account/uuid/{uuid}/roles:
    get:
      operationId: getAccountRoles
      description: d
      tags:
        - Account
      parameters:
        - in: path
          name: uuid
          required: true
          description: d
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/AccountRoleDTO"

  /api/store/:
    get:
      operationId: getStores
      description: d
      tags:
        - Store
      parameters:
        - in: query
          name: id
          required: false
          description: d
          schema:
            type: integer
            format: int64
        - in: query
          name: country
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: city
          required: false
          description: d
          schema:
            type: string
        - in: query
          name: street
          required: false
          description: d
          schema:
            type: string
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/StoreDTO"

  /api/store/id/{id}:
    get:
      operationId: getStoreById
      description: d
      tags:
        - Store
      parameters:
        - in: path
          name: id
          required: true
          description: d
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoreDTO"
        404:
          description: d

  /api/store/id/{id}/registers/:
    get:
      operationId: getRegistersByStore
      description: d
      tags:
        - Store
      parameters:
        - in: path
          name: id
          required: true
          description: d
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/RegisterDTO"
        404:
          description: d

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ConnectionDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        target:
          $ref: "#/components/schemas/EntityTargetDTO"
        instance:
          $ref: "#/components/schemas/InstanceDetailsDTO"
        acquiredAt:
          type: string
          format: date-time
        heartbeatAt:
          type: string
          format: date-time

    LockDTO:
      type: object
      description: d
      properties:
        target:
          $ref: "#/components/schemas/EntityTargetDTO"
        instanceUUID:
          type: string
          format: uuid
        acquiredAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

    EntityTargetDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        type:
          $ref: "#/components/schemas/TargetType"

    TargetType:
      type: string
      description: d
      enum:
        - STORE
        - REGISTER
        - ACCOUNT

    InstanceDetailsDTO:
      type: object
      description: d
      properties:
        uuid:
          type: string
          format: uuid
        host:
          type: string
        server:
          type: string
        port:
          type: integer
          format: int64

    AccountDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
          format: uuid
        username:
          type: string
        password:
          type: string
          format: password
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        phone:
          type: string
          format: phone
        email:
          type: string
          format: email

    AccountRoleDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        role:
          $ref: "#/components/schemas/Role"

    Role:
      type: string
      description: d
      enum:
        - CASHIER
        - ADMIN
        - SYSTEM

    StoreDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        country:
          type: string
        city:
          type: string
        street:
          type: string
        streetNumber:
          type: string

    RegisterDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        store:
          $ref: "#/components/schemas/StoreDTO"