openapi: 3.0.0

info:
  title: Store
  description: Store
  version: 1.0.0

tags:
  - name: Article
    description: Operations related to Articles
  - name: Receipt
    description: Operations related to Receipts

security:
  - bearerAuth: [ ]

paths:
  /api/article/:
    get:
      operationId: getArticles
      description: d
      tags:
        - Article
      parameters:
        - in: query
          name: id
          required: false
          description: d
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  $ref: "#/components/schemas/ArticleDTO"

  /api/article/id/{id}:
    get:
      operationId: getArticleById
      description: d
      tags:
        - Article
      parameters:
        - in: path
          name: id
          required: true
          description: d
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ArticleDTO"
        404:
          description: d

  /api/article/gtin/{gtin}:
    get:
      operationId: getArticleByGtin
      description: d
      tags:
        - Article
      parameters:
        - in: path
          name: gtin
          required: true
          description: d
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ArticleDTO"
        404:
          description: d

  /api/receipt/:
    post:
      operationId: postReceipt
      description: d
      tags:
        - Receipt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptDTO"
      responses:
        200:
          description: d
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ReceiptDTO"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ArticleDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        gtin:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        manufacturer:
          type: string
        supplier:
          type: string
        unit:
          type: string
        purchasePrice:
          type: number
          format: double
        sellingPrice:
          type: number
          format: double
        taxRate:
          type: number
          format: double
        stock:
          type: integer
          format: int64
        isAvailable:
          type: boolean
        isDeposit:
          type: boolean

    ReceiptDTO:
      type: object
      description: d
      properties:
        id:
          type: integer
          format: int64
        storeId:
          type: integer
          format: int64
        registerId:
          type: integer
          format: int64
        cashierId:
          type: integer
          format: int64