# Application
spring.application.name=orchestrator
spring.profiles.default=local
spring.profiles.active=local

# Oauth2
spring.security.oauth2.client.registration.keycloak.client-id=orchestrator-app
spring.security.oauth2.client.registration.keycloak.client-secret=qK8jKAMhQnzRWHMlmNNw6iILoaW65U2I