# Postgres
spring.datasource.url=jdbc:postgresql://ep-still-sky-agzvzwl9-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nb2oUpM1CmPX

# RabbitMQ
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.host=cow.rmq2.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=tgamtfjc
spring.rabbitmq.password=LGl-i3KF-JuaNxoPrUGCNsffR9AYfo-i
spring.rabbitmq.virtual-host=tgamtfjc