# Application
spring.application.name=orchestrator
spring.profiles.default=local
spring.profiles.active=local

# Oauth2
vendix.keycloak.client.app-name=orchestrator-app
vendix.keycloak.client.web-name=orchestrator-web
## Orchestrator Web
spring.security.oauth2.client.registration.orchestrator-web.client-id=orchestrator-web
spring.security.oauth2.client.registration.orchestrator-web.client-secret=V3tBSZATSHRtNM63VGkeldXRXisQo1Yp
spring.security.oauth2.client.registration.orchestrator-web.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.orchestrator-web.scope=openid,profile,email
spring.security.oauth2.client.registration.orchestrator-web.provider=keycloak
## Orchestrator App
spring.security.oauth2.client.registration.orchestrator-app.client-id=orchestrator-app
spring.security.oauth2.client.registration.orchestrator-app.client-secret=YhM12hzAunSCdsvbJhrg1eApnk3xmS5s
spring.security.oauth2.client.registration.orchestrator-app.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.orchestrator-app.scope=openid,profile,email
spring.security.oauth2.client.registration.orchestrator-app.provider=keycloak