<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.fhdw.vendix</groupId>
        <artifactId>store-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>store-ui</artifactId>
    <packaging>jar</packaging>

    <name>store-ui</name>
    <description>store-ui</description>

    <dependencies>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>store-core</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
