<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.fhdw.vendix</groupId>
        <artifactId>commons-spring-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>commons-spring-starter</artifactId>
    <packaging>jar</packaging>

    <name>commons-spring-starter</name>
    <description>commons-spring-starter</description>

    <dependencies>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-api</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-core</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-spring-security</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-spring-data</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-spring-web</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-spring-vaadin</artifactId>
        </dependency>

        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-spring-app</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.loki4j</groupId>
            <artifactId>loki-logback-appender</artifactId>
        </dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>