<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.fhdw.vendix</groupId>
        <artifactId>commons-spring-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>commons-spring-starter</artifactId>
    <packaging>jar</packaging>

    <name>commons-spring-starter</name>
    <description>commons-spring-starter</description>

    <dependencies>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-security-spring</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-spring-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.fhdw.vendix</groupId>
            <artifactId>commons-ui-vaadin</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.wimdeblauwe</groupId>
            <artifactId>error-handling-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>