# Spring
spring.threads.virtual.enabled=true

# Monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=read_only

# Consul
spring.cloud.loadbalancer.enabled=false