openapi: 3.0.0

info:
  title: Orchestrator API
  description: This API provides operations for managing service registry, locks, accounts, and stores.
  version: 1.0.0

tags:
  - name: Registry
    description: Operations related to service registry.
  - name: DistributedLock
    description: Operations related to resource locking.
  - name: Store
    description: Operations related to stores.
  - name: Register
    description: Operations related to registers.

servers:
  - url: http://localhost:8080
    description: Local development server.

security:
  - bearerAuth: [ ]

paths:
  /api/registry/register:
    $ref: './paths/registry_register.yaml'
  /api/registry/heartbeat/{instanceId}:
    $ref: './paths/registry_heartbeat.yaml'
  /api/lock:
    $ref: './paths/lock.yaml'
  /api/lock/type/{type}:
    $ref: './paths/lock_type.yaml'
  /api/lock/type/{type}/id/{id}:
    $ref: './paths/lock_type_id.yaml'
  /api/lock/uuid/{uuid}:
    $ref: './paths/lock_uuid.yaml'
  /api/store/locked:
    $ref: './paths/store_locked.yaml'
  /api/store/unlocked:
    $ref: './paths/store_unlocked.yaml'
  /api/store/id/{id}:
    $ref: './paths/store_id.yaml'
  /api/store/{storeId}/register:
    $ref: './paths/store_storeId_register.yaml'
  /api/store/{storeId}/register/locked:
    $ref: './paths/store_storeId_register_locked.yaml'
  /api/store/{storeId}/register/unlocked:
    $ref: './paths/store_storeId_register_unlocked.yaml'
  /api/register/id/{id}:
    $ref: './paths/register_id.yaml'
  /api/register/locked:
    $ref: './paths/register_locked.yaml'
  /api/register/unlocked:
    $ref: './paths/register_unlocked.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Bearer token for authentication. Example: 'Bearer {token}'"

  schemas:
    RegistrationRequest:
      $ref: './components/schemas/RegistrationRequest.yaml'
    DistributedLockDTO:
      $ref: './components/schemas/DistributedLockDTO.yaml'
    EntityTargetDTO:
      $ref: './components/schemas/EntityTargetDTO.yaml'
    TargetType:
      $ref: './components/schemas/TargetType.yaml'
    StoreDTO:
      $ref: './components/schemas/StoreDTO.yaml'
    RegisterDTO:
      $ref: './components/schemas/RegisterDTO.yaml'