springdoc:
  group-configs:
    - group: orchestrator-api
      packages-to-scan: de.fhdw.vendix.commons.spring.web.api.orchestrator
    - group: register-api
      packages-to-scan: de.fhdw.vendix.commons.spring.web.api.register
    - group: store-api
      packages-to-scan: de.fhdw.vendix.commons.spring.web.api.store