<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.fhdw.vendix</groupId>
        <artifactId>commons-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>commons-api</artifactId>
    <packaging>jar</packaging>

    <name>commons-api</name>
    <description>commons-api</description>

    <properties>
        <openapi-domain.name>account</openapi-domain.name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

<!--            <plugin>-->
<!--                <groupId>org.openapitools</groupId>-->
<!--                <artifactId>openapi-generator-maven-plugin</artifactId>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>generate-${openapi-domain.name}-api</id>-->
<!--                        <phase>generate-sources</phase>-->
<!--                        <goals>-->
<!--                            <goal>generate</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <inputSpec>-->
<!--                                ${project.basedir}/src/main/resources/openapi/${openapi-domain.name}.yaml-->
<!--                            </inputSpec>-->

<!--                            <output>-->
<!--                                ${project.build.directory}/generated-sources/openapi/${openapi-domain.name}-->
<!--                            </output>-->

<!--                            <configurationFile>-->
<!--                                ${project.basedir}/src/main/resources/openapi/config/spring-config.json-->
<!--                            </configurationFile>-->

<!--                            <generatorName>spring</generatorName>-->

<!--                            <apiPackage>${project.groupId}.${openapi-domain.name}.api</apiPackage>-->
<!--                            <modelPackage>${project.groupId}.${openapi-domain.name}.dto</modelPackage>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
        </plugins>
    </build>
</project>